version: "3.3"
services:
  caddy:
    image: caddy:2.1.1-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/ubuntu/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /home/ubuntu/caddy/data:/data
    restart: always
  aveflask:
    image: local/aveflask
    volumes:
      - /home/ubuntu/AVE-usergames:/AVE-usergames
    restart: always